spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.fulfill.notificationservice.event
        spring.json.value.default.type: com.fulfill.notificationservice.event.OrderCreatedEvent
        spring.json.use.type.headers: false

fulfill:
  kafka:
    topics:
      order-created: ${ORDER_CREATED_TOPIC:order-created}
