spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fulfill_orders}
    username: ${SPRING_DATASOURCE_USERNAME:fulfill}
    password: ${SPRING_DATASOURCE_PASSWORD:fulfill}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
